# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -l mres=8G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N blast_all
#$ -o blast_all.log
#
# ----------------Modules------------------------- #
module load bioinformatics/blast
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#

# Directory with the fasta files
DIR=fastas
if [ ! -d ${DIR} ]; then
  echo "ERROR: The directory you entered was not found: ${DIR}"
  exit 1
fi

# Blast DB (path/DB_name)
DB=blastdb/difficile

# Output directory for fasta results
OUTDIR=blast_results
if [ ! -d ${OUTDIR} ]; then
  mkdir ${OUTDIR}
fi

echo "BLAST of fasta files in ${DIR} against ${DB}"
for FILE in ${DIR}/*.fasta; do
  FILENAME=$(basename ${FILE})
  GENENAME=$(echo ${FILENAME} | sed 's/.fasta//')
  echo "${FILENAME}, gene: ${GENENAME}, output: ${OUTDIR}/${GENENAME}.csv"
  blastn -db ${DB} -query ${FILE} -outfmt 10 -max_target_seqs 25 -out ${OUTDIR}/${GENENAME}.csv
done

#
echo = `date` job $JOB_NAME done